In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.6


In [7]:

arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)


arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr3)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# arange -> similar to Python range() but returns an array
range_arr = np.arange(0, 10, 2)  
print("arange array:", range_arr)

lin_arr = np.linspace(0, 1, 5)    
print("linspace array:", lin_arr)

rand_arr = np.random.rand(2, 3)     
randint_arr = np.random.randint(1, 100, size=(5, 3))  
print("Random float array:\n", rand_arr)

print("Random integer array:\n", randint_arr)

arange array: [0 2 4 6 8]
linspace array: [0.   0.25 0.5  0.75 1.  ]
Random float array:
 [[0.18588082 0.72202157 0.5600865 ]
 [0.14888262 0.46328817 0.29327131]]
Random integer array:
 [[33 98 33]
 [79 35 75]
 [58 13 70]
 [93 91 21]
 [43 78 48]]


In [ ]:
exercise1_a = np.zeros((4, 4))
exercise1_b = np.arange(10, 51, 5)
print(exercise1_a)
print(exercise1_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20 25 30 35 40 45 50]


In [15]:
sample = np.array([[1, 2, 3], [7,8, 9]])

print("Array:\n", sample)
print("Shape:", sample.shape)      
print("Dimensions:", sample.ndim)  
print("Size:", sample.size)       
print("Data type:", sample.dtype)

Array:
 [[1 2 3]
 [7 8 9]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


In [17]:
x = np.array([13, 20, 35, 40])
y = np.array([1, 2, 3, 4])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)

Addition: [14 22 38 44]
Subtraction: [12 18 32 36]
Multiplication: [ 13  40 105 160]
Division: [13.         10.         11.66666667 10.        ]
Power: [ 169  400 1225 1600]


In [19]:
data = np.array([4, 8, 15, 16, 25, 40])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))

Sum: 108
Mean: 18.0
Minimum: 4
Maximum: 40
Standard deviation: 11.846237095944574
Variance: 140.33333333333334
